--"RESET WITH LIST" --made by yuuiko - 25/6/2020use framework "IOBluetooth"use scripting additionsset deviceList to current application's IOBluetoothDevice's pairedDevices()set devNames to (deviceList's valueForKey:"name") as listset widgetVariable to "AirPodsWg_DevceName"--1: GET STORED NAME / ASK TO SET NAME IF NOT PRESENTtell application "BetterTouchTool"	try		set LclAirPodsName to get_string_variable widgetVariable	end tryend tell-- first time insert name window--tell application "BetterTouchTool" to choose from list devNames with title "Setup Bluetooth Widget" OK button name "Connect" cancel button name "Cancel" with prompt "Setup this widget for:--" default items LclAirPodsName without multiple selections allowed and empty selection allowedtell application "BetterTouchTool" to set_persistent_string_variable widgetVariable to ""tell application "BetterTouchTool" to choose from list devNames with title "Setup Bluetooth Widget" OK button name "Connect" cancel button name "Clear" with prompt "Setup this widget for:
" without multiple selections allowed and empty selection allowedif the result is not false then	try		set SelectedDeviceName to item 1 of the result				--store BTT variable		tell application "BetterTouchTool" to set_persistent_string_variable widgetVariable to SelectedDeviceName			on error --error setting the variable		--show error alert window 		tell application "BetterTouchTool" to display dialog "There was an error while setting up the Bluetooth widget. 

Try again, or contact \"yyuuiko\" at the BTT forums or AQT Discord if the issue persists." with title "Bluetooth Widget" with icon note buttons {"OK"} default button "OK"	end try	return my connectAirPods()else	returnend if-- 2: CONNECT AIRPODS BASED ON STORED VARIABLEon connectAirPods(LclAirPodsName, widgetVariable) --Connect AirPods Function	tell application "BetterTouchTool"		try			set LclAirPodsName to get_string_variable widgetVariable		end try	end tell		--activate application "SystemUIServer"	tell application "System Events"		tell process "SystemUIServer"			-- Working CONNECT Script.  Goes through the following:			-- Clicks on Bluetooth Menu (OSX Top Menu Bar)			--    => Clicks on device based on variable name			--      => Clicks on Connect Item			try				set btMenu to (menu bar item 1 of menu bar 1 whose description contains "bluetooth")				tell btMenu					click					tell (menu item LclAirPodsName of menu 1)						click						if exists menu item "Connect" of menu 1 then							click menu item "Connect" of menu 1							return LclAirPodsName & "
Connecting..."						else							click menu item "Disconnect" of menu 1							return LclAirPodsName & "
Disconnecting..."						end if					end tell				end tell							on error								----------------- error "connection" alert window ---------------				tell application "BetterTouchTool" to display dialog "Bluetooth Widget could not find your device \"" & LclAirPodsName & "\".

- Make sure it is paired, then try again
- Enable the bluetooth menubar item in System Preferences
- Reset widget and check device name" with title "Bluetooth Widget" with icon note buttons {"Reset Widget", "OK"} default button "OK"								----------------- error "connection" alert window ---------------								if the button returned of the result is "Reset Widget" then					tell application "BetterTouchTool" to trigger_named resetAction				else --if window pressed OK					return				end if			end try		end tell	end tell	returnend connectAirPods